Repository p-amol/pyadps, pull requests merged in 2025-03, with the labels that each got.

#86 datatype is modified to read corrupted files.
  src/pyadps/utils/pyreadrdi.py
Labels: bug

#87 Testing pyreadrdi
  poetry.lock
  pyproject.toml
  src/pyadps/pages/01_Read_File.py
  src/pyadps/pages/04_Sensor_Health.py
  src/pyadps/pages/06_Profile_Test.py
  src/pyadps/pages/07_Velocity_Test.py
  src/pyadps/pages/08_Write_File.py
  src/pyadps/pages/09_Auto_process.py
  src/pyadps/utils/autoprocess.py
  src/pyadps/utils/pyreadrdi.py
  src/pyadps/utils/script.py
  src/pyadps/utils/velocity_test.py
  tests/test_data/ensemble.000
  tests/test_pyreadrdi.py
Labels: testing

#88 array value set to -32768 which i missed in the previous commit
  src/pyadps/utils/pyreadrdi.py
Labels: bug

#89 The code adjusted for version compatibility.
  src/pyadps/utils/pyreadrdi.py
Labels: bug

#90 Fixed Leader .nc download feature
  src/pyadps/pages/01_Read_File.py
  src/pyadps/pages/03_Download_Raw_File.py
  src/pyadps/utils/writenc.py
Labels: enhancement

#92 Added echo, correlation, pgood in processed file
  src/pyadps/pages/08_Write_File.py
  src/pyadps/utils/writenc.py
Labels: enhancement

#94 Testing pyreadrdi
  src/pyadps/pages/01_Read_File.py
  src/pyadps/pages/03_Download_Raw_File.py
  src/pyadps/pages/08_Write_File.py
  src/pyadps/utils/pyreadrdi.py
  src/pyadps/utils/writenc.py
  tests/conftest.py
  tests/test_data/ensemble.000
  tests/test_pyreadrdi.py
Labels: testing

#97 Auto_process added fixed leader.nc download & updated config file gen…
  src/pyadps/pages/08_Write_File.py
  src/pyadps/utils/autoprocess.py
Labels: enhancement

#100 Modified Regrid to accept both uniform and non-uniform files.
  src/pyadps/pages/06_Profile_Test.py
  src/pyadps/utils/profile_test.py
Labels: bug
